//
//  creditsPage.swift
//  Period.
//
//  Created by paige randell on 7/19/24.
//

import SwiftUI

struct creditsPage: View {
    var body: some View {
        ZStack {
            Color.init(red: 255/255, green: 206/255, blue: 215/255).edgesIgnoringSafeArea(.all)
            VStack {
                Text("Credits")
                    .font(.custom("Italiana-Regular", size: 35))
                
                Spacer()
                    .frame(height: 15.0)
                Text("Websites & Facts")
                    .font(.custom("Italiana-Regular", size: 20))
                    .fontWeight(.bold)
                    .underline(true, color:Color(red: 255 / 255, green: 103 / 255, blue: 103 / 255))
                    .padding(.bottom)
                
                Text("Eatwell, H. (2023, July 24). Menstrual cycle tracking: How to track your periods and why it’s important. Nuffield Health. https://www.nuffieldhealth.com/article/how-track-periods-menstrual-cycle")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 22.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("Anzilotti, A. W. (Ed.). (2019b, October). Tampons, pads, and other period supplies (for teens) | nemours kidshealth. KidsHealth. https://kidshealth.org/en/teens/supplies.html")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 19.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("Scaccia, A. (2019, April 9). Menstrual cups: How to use, benefits, and more. Healthline. https://www.healthline.com/health/womens-health/menstrual-cup")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 20.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("Healthy New Jersey. Period underwear. (n.d.). https://www.nj.gov/health/womenshealth/reproductive-health/periods-menstruation/period-products/period-underwear.shtml")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 20.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("Guster, T. (2023). Schedule your appointment online. Should you try period underwear? https://www.piedmont.org/living-real-change/should-you-try-period-underwear")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 20.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("Greenlight. (2024, March 27). Understanding the pink tax: A guide for parents. Debit Card for Kids and Teens. https://greenlight.com/learning-center/glossary/pink-tax ")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 21)
                    Spacer()
                        .frame(height: 10.0)
                Text("Tampax, P. & G. (2020, May 18). Period Hacks: How to Feel Better on Your Period. https://tampax.com/en-us/period-health/how-to-feel-better-on-your-period/")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 20.5)
                    Spacer()
                        .frame(height: 10.0)
                Text("WASH, CDC. (2024, May 7). Healthy habits: Menstrual hygiene. Centers for Disease Control and Prevention. https://www.cdc.gov/hygiene/about/menstrual-hygiene.html")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 20.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("Bowman, J. (2022, January 3). How to make a homemade heating pad. Healthline. https://www.healthline.com/health/pain-relief/how-to-make-a-homemade-heating-pad")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 20.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("Ayres, I. (2022, October 12). Which retailers charge the largest “pink tax”? Forbes. https://www.forbes.com/sites/whynot/2016/01/07/which-retailers-charge-the-largest-pink-tax/")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 16)
                    Spacer()
                        .frame(height: 10.0)
                Text("Redd, N. (2018, July 10). The best period underwear. The New York Times. https://www.nytimes.com/wirecutter/reviews/thinx-period-panties/")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 17.0)
                    Spacer()
                        .frame(height: 10.0)
               
                Text("Image Credits")
                    .font(.custom("Italiana-Regular", size: 20))
                    .fontWeight(.bold)
                    .underline(true, color:Color(red: 255 / 255, green: 103 / 255, blue: 103 / 255))
                    .padding(.bottom)
                Text("LifeMessages. (n.d.). Cheerful Aesthetic Pink Tones Doodles in Vibrant and Pastel Colors. Redbubble. LifeMessages. Retrieved from https://www.redbubble.com/i/art-board-print/Cheerful-Aesthetic-Pink-Tones-Doodles-in-Vibrant-and-Pastel-Colors-by-LifeMessages/141048163.8DB3C")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 18.0)
                    Spacer()
                        .frame(height: 10.0)
                Text("[deleted]. (2022). [product] pink tax. Reddit. [deleted]. Retrieved July 19, 2024, from https://www.reddit.com/r/pointlesslygendered/comments/u17bd2/product_pink_tax/")
                    .font(.custom("Italiana-Regular", size: 13.0))
                        .fontWeight(.bold)
                        .foregroundColor(Color(.black))
                        .padding(.horizontal, 18.0)
                    Spacer()
                        .frame(height: 10.0)


            }
        }
    }
}

#Preview {
    creditsPage()
}
